#######################################################
#
# AbstractNegoParty.py
# Python implementation of the Class AbstractNegoParty
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.AcceptanceStrategyInterface import AcceptanceStrategyInterface
from core.BiddingStrategyInterface import BiddingStrategyInterface
from core.ElicitationStrategyInterface import ElicitationStrategyInterface
from core.OpponentModelInterface import OpponentModelInterface
from core.UserModelInterface import UserModelInterface
from core.NegoPartyInterface import NegoPartyInterface


class AbstractNegoParty(NegoPartyInterface):
    m_ElicitationStrategyInterface = ElicitationStrategyInterface()

    m_UserModelInterface = UserModelInterface()

    m_BiddingStrategyInterface = BiddingStrategyInterface()

    m_OpponentModelInterface = OpponentModelInterface()

    m_AcceptanceStrategyInterface = AcceptanceStrategyInterface()

    def get_party_name() -> String:
        pass

    def set_acceptance_strategy(acceptance_strategy: AcceptanceStrategyInterface) -> void:
        pass

    def set_bidding_strategy(bidding_strategy: BiddingStrategyInterface) -> void:
        pass

    def set_elicitation_strategy(elicitation_strategy: ElicitationStrategyInterface) -> void:
        pass

    def set_opponent_model(opponent_model: OpponentModelInterface) -> void:
        pass

    def set_user_model(usel_model: UserModelInterface) -> void:
        pass

    def send_bid() -> Bid:
        pass
