#######################################################
# 
# AbstractNegoParty.py
# Python implementation of the Class AbstractNegoParty
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:31 Ş.Ù
# Original author: DP
# 
#######################################################
from core.AcceptanceStrategy import AcceptanceStrategy
from core.BiddingStrategy import BiddingStrategy
from core.ElicitationStrategy import ElicitationStrategy
from core.OpponentModel import OpponentModel
from core.UserModel import UserModel
from core.NegoPartInterface import NegoPartInterface

class AbstractNegoParty(NegoPartInterface):
    m_ElicitationStrategy= ElicitationStrategy()

    m_UserModel= UserModel()

    m_BiddingStrategy= BiddingStrategy()

    m_OpponentModel= OpponentModel()

    m_AcceptanceStrategy= AcceptanceStrategy()

    def get_party_name() -> String:
        pass

    def set_acceptance_strategy(acceptance_strategy : AcceptanceStrategy) -> void:
        pass

    def set_bidding_strategy(bidding_strategy : BiddingStrategy) -> void:
        pass

    def set_elicitation_strategy(elicitation_strategy : ElicitationStrategy) -> void:
        pass

    def set_opponent_model(opponent_model : OpponentModel) -> void:
        pass

    def set_user_model(usel_model : UserModel) -> void:
        pass

    def send_bid() -> Bid:
        pass