#######################################################
#
# AbstractNegoParty.py
# Python implementation of the Class AbstractNegoParty
# Generated by Enterprise Architect
# Created on:      26-����-2022 01:26:22 �.�
# Original author: Arash Ebrahimnezhad
#
#######################################################
from core.AcceptanceStrategy import AcceptanceStrategyInterface
from core.BiddingStrategy import BiddingStrategyInterface
from core.ElicitationStrategy import ElicitationStrategyInterface
from core.OpponentModel import OpponentModelInterface
from core.UserModel import UserModelInterface
from core.NegoPartInterface import NegoPartInterface


class AbstractNegoParty(NegoPartInterface):
    m_ElicitationStrategyInterface = ElicitationStrategyInterface()

    m_UserModelInterface = UserModelInterface()

    m_BiddingStrategyInterface = BiddingStrategyInterface()

    m_OpponentModelInterface = OpponentModelInterface()

    m_AcceptanceStrategyInterface = AcceptanceStrategyInterface()

    def get_party_name() -> String:
        pass

    def set_acceptance_strategy(acceptance_strategy: AcceptanceStrategyInterface) -> void:
        pass

    def set_bidding_strategy(bidding_strategy: BiddingStrategyInterface) -> void:
        pass

    def set_elicitation_strategy(elicitation_strategy: ElicitationStrategyInterface) -> void:
        pass

    def set_opponent_model(opponent_model: OpponentModelInterface) -> void:
        pass

    def set_user_model(usel_model: UserModelInterface) -> void:
        pass

    def send_bid() -> Bid:
        pass
