#######################################################
# 
# AcceptanceStrategy.py
# Python implementation of the Interface AcceptanceStrategyInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 02:24:13 Þ.Ù
# Original author: DP
# 
#######################################################
from core.Offer import Offer

class AcceptanceStrategyInterface:
    def is_acceptable(offer : Offer) -> int:
        """this method returns 0 refer to reject opponent's offer or 1 refer to accept
        opponent offer.
        """
        pass