#######################################################
# 
# AcceptanceStrategy.py
# Python implementation of the Interface AcceptanceStrategy
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:34 Þ.Ù
# Original author: DP
# 
#######################################################
from core.Offer import Offer

class AcceptanceStrategy:
    def is_acceptable(offer : Offer) -> int:
        """this method returns 0 refer to reject opponent's offer or 1 refer to accept
        opponent offer.
        """
        pass