#######################################################
# 
# AnalyseMan.py
# Python implementation of the Class AnalyseMan
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 02:24:13 Ş.Ù
# Original author: Arash Ebrahimnezhad
# 
#######################################################


class AnalyseMan:
    """<span dir="rtl">Çíä ˜áÇÓ Èå ãíÒ ãĞÇ˜Ñå¡ ÊÑÌíÍÇÊ ÍÑíİÇä¡ ÊÎãíä åÇí Âä åÇ ÏÓÊÑÓí
    ÏÇÑÏ æ ÈÇ ÊæÌå Èå ÂäåÇ ãí ÊæÇäÏ ÂäÇáíÒ ÑÇ ÇäÌÇã ÏåÏ.</span>
    """
    pass