#######################################################
# 
# Bid.py
# Python implementation of the Class Bid
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 02:24:13 Þ.Ù
# Original author: DP
# 
#######################################################


class Bid:
    def get_values() -> Dict:
        pass