#######################################################
# 
# BiddingStrategy.py
# Python implementation of the Interface BiddingStrategy
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:36 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Bid import Bid

class BiddingStrategy:
    def send_bid(timline) -> Bid:
        pass