#######################################################
# 
# BiddingStrategy.py
# Python implementation of the Interface BiddingStrategyInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 01:26:22 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Bid import Bid

class BiddingStrategyInterface:
    def send_bid(timline) -> Bid:
        pass