#######################################################
#
# ElicitationStrategy.py
# Python implementation of the Interface ElicitationStrategyInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: Arash Ebrahimnezhad
#
#######################################################
from core.Offer import Offer
from abc import ABC, abstractmethod


class ElicitationStrategyInterface(ABC):

    @abstractmethod
    def ask_offer_rank_from_user(self, offer: Offer) -> list:
        """This method returns a list of ranked bids
        """
        raise NotImplementedError()

    def ask_offer_utility_from_user(self, offer: Offer) -> float:
        raise NotImplementedError()
