#######################################################
# 
# ElicitationStrategy.py
# Python implementation of the Interface ElicitationStrategy
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:48 Ş.Ù
# Original author: Arash Ebrahimnezhad
# 
#######################################################
from core.Offer import Offer

class ElicitationStrategy:
    def ask_offer_rank_from_user(offer : Offer) -> List:
        """This method returns a list of ranked bids
        """
        pass

    def ask_offer_utility_from_user(offer : Offer) -> float:
        pass