#######################################################
#
# NegoPartInterface.py
# Python implementation of the Interface NegoPartInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################


class NegoPartyInterface:
    def send_bid() -> Bid:
        pass
