#######################################################
#
# NegoPartyAbstract.py
# Python implementation of the Class NegoPartyAbstract
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.UtiltiySpace import UtiltiySpace


class NegoPartyAbstract:
    pass
