#######################################################
# 
# NegoParty2.py
# Python implementation of the Class NegoParty2
# Generated by Enterprise Architect
# Created on:      26-„«—”-2022 12:56:56 ﬁ.Ÿ
# Original author: DP
# 
#######################################################


class NegoParty2:
    pass