#######################################################
# 
# NegoPartInterface.py
# Python implementation of the Interface NegoPartInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:52 Ş.Ù
# Original author: DP
# 
#######################################################


class NegoPartInterface:
    def send_bid() -> Bid:
        pass