#######################################################
#
# NegoEnv.py
# Python implementation of the Class NegoEnv
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.NegoTable import NegoTable
from core.ProtocolInterface import ProtocolInterface
from core.AbstractNegoParty import AbstractNegoParty


class NegoEnv:
    m_NegoTable = NegoTable()

    m_ProtocolInterface = ProtocolInterface()

    m_AbstractNegoParty = AbstractNegoParty()

    def get_name() -> String:
        pass

    def get_nego_table() -> NegoTable:
        pass

    def get_protocol() -> ProtocolInterface:
        pass
