#######################################################
#
# NegoPartInterface.py
# Python implementation of the Interface NegoPartInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from Bid import Bid
from abc import ABC, abstractmethod


class NegoPartyInterface(ABC):

    @abstractmethod
    def send_bid() -> Bid:
        raise NotImplementedError()
