#######################################################
#
# NegoEnv.py
# Python implementation of the Class NegoEnv
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.NegoTable import NegoTable
from core.ProtocolInterface import ProtocolInterface
from core.AbstractNegoParty import AbstractNegoParty


class NegoEnv:
    nego_table = NegoTable()
    protocol_interface = ProtocolInterface()
    nego_party = AbstractNegoParty()

    def get_name(self) -> str:
        pass

    def get_nego_table(self) -> NegoTable:
        pass

    def get_protocol(self) -> ProtocolInterface:
        pass
