#######################################################
# 
# NegoParty.py
# Python implementation of the Class NegoParty
# Generated by Enterprise Architect
# Created on:      26-„«—”-2022 12:56:55 ﬁ.Ÿ
# Original author: DP
# 
#######################################################


class NegoParty:
    pass