#######################################################
#
# NegoTable.py
# Python implementation of the Class NegoTable
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.AnalyseMan import AnalyseMan
from core.ProtocolInterface import ProtocolInterface
from core.TimeLine import TimeLine


class NegoTable:
    def get_negotiation_state(self) -> int:
        pass

    def get_offers_on_table(self, party: str):
        pass

    def get_parties(self) -> tuple:
        pass

    def get_time(self) -> TimeLine:
        pass
