#######################################################
# 
# NegoPartyAbstract.py
# Python implementation of the Class NegoPartyAbstract
# Generated by Enterprise Architect
# Created on:      26-„«—”-2022 01:26:22 ﬁ.Ÿ
# Original author: DP
# 
#######################################################
from core.UtiltiySpace import UtiltiySpace

class NegoPartyAbstract:
    pass