#######################################################
# 
# NegoTable.py
# Python implementation of the Class NegoTable
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:57 Þ.Ù
# Original author: DP
# 
#######################################################
from core.AnalyseMan import AnalyseMan
from core.Protocol import Protocol
from core.TimeLine import TimeLine

class NegoTable:
    def get_negotiation_state() -> int:
        pass

    def get_offers_on_table(party : String) -> void:
        pass

    def get_parties() -> Tuple:
        pass

    def get_time() -> TimeLine:
        pass