#######################################################
#
# Offer.py
# Python implementation of the Class Offer
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Bid import Bid
from core.TimeLine import TimeLine


class Offer:
    """bid and the time that bid take on negotiation table.
    """
    time_line = TimeLine()
    bid = Bid()

    def get_bid(self) -> Bid:
        pass

    def get_time(self) -> TimeLine:
        pass
