#######################################################
# 
# OpponentModel.py
# Python implementation of the Interface OpponentModel
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:56:59 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Preference import Preference
from core.Offer import Offer

class OpponentModel:
    def get_initial_opponent_preference() -> Preference:
        pass

    def get_preference() -> Preference:
        pass

    def update_preferece(offer : Offer) -> Preference:
        pass