#######################################################
# 
# OpponentModel.py
# Python implementation of the Interface OpponentModelInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 01:26:23 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Preference import Preference
from core.Offer import Offer

class OpponentModelInterface:
    def get_initial_opponent_preference() -> Preference:
        pass

    def get_preference() -> Preference:
        pass

    def update_preferece(offer : Offer) -> Preference:
        pass