#######################################################
#
# OpponentModel.py
# Python implementation of the Interface OpponentModelInterface
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Preference import Preference
from core.Offer import Offer


class OpponentModelInterface:
    def get_initial_opponent_preference() -> Preference:
        pass

    def get_preference() -> Preference:
        pass

    def update_preferece(offer: Offer) -> Preference:
        pass
