#######################################################
# 
# Preference.py
# Python implementation of the Class Preference
# Generated by Enterprise Architect
# Created on:      26-„«—”-2022 02:24:13 ﬁ.Ÿ
# Original author: Arash Ebrahimnezhad
# 
#######################################################


class Preference:
    """
    preference has its own data structure and when an object asks preference, it returns that specific data structure.
    In the following there is an example:
    preference = {
        'Brand': [0.45, {'Lenovo': 10, 'Assus': 20, 'Mac': 30}],
        'Monitor': [0.18, {'15': 30, '10': 25, '11': 20}],
        'HDD': [0.38, {'1T': 25, '2T': 32, '3T': 35}]
    }
    """

    def __init__(self, preference):
        self.preference = preference

    def get_preference(self):
        return self.preference

    def get_issue_weight(self, issue: str):
        return self.preferenc[issue][0]

    def get_issue_item_value(self, issue: str, value: str):
        """
        :param issue: str
        :param value: str
        :return: int
        """
        return self.preferenc[issue][1][value]
