#######################################################
# 
# Preference.py
# Python implementation of the Class Preference
# Generated by Enterprise Architect
# Created on:      26-„«—”-2022 12:57:00 ﬁ.Ÿ
# Original author: DP
# 
#######################################################


class Preference:
    def get_preference():
        pass