#######################################################
# 
# ProtocolInterface.py
# Python implementation of the Interface ProtocolInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 02:24:13 Þ.Ù
# Original author: DP
# 
#######################################################
from core.TimeLine import TimeLine

class ProtocolInterface:
    def ask_bid_from_party() -> void:
        """This method ask an bid from party according to order and negotiation state then
        convert it to offer and add it to the table offers and update negotiation state
    
           negotiation state will be 1 if the last parties' offer are same
           negotiation state will be 0 if the last parties' offer are not same
           negotiation state will be -1 if the one of last parties' offer's Bid is {}
        """
        pass

    def determine_order() -> String:
        pass

    def get_offer_on_table(party_name : String) -> Tuple:
        """This method gets a party name in string type and returns a tuple of offers
        related to the party name that has got through the object that has called the
        method.
           Before returning the offers, the method checks out whether the object that
        has called the method has authority to access the offers or not? if there is no
        permission it returns an error.
        """
        pass

    def get_time_line() -> TimeLine:
        pass