#######################################################
# 
# TimeLine.py
# Python implementation of the Class TimeLine
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 01:26:23 Ş.Ù
# Original author: DP
# 
#######################################################


class TimeLine:
    def get_time() -> double:
        pass