#######################################################
# 
# User.py
# Python implementation of the Interface UserInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 01:26:23 Þ.Ù
# Original author: Arash Ebrahimnezhad
# 
#######################################################
from core.Preference import Preference
from core.Offer import Offer

class UserInterface:
    def get_initial_bids_rank() -> List:
        """This method returns list of ranked bids in uncertain situation.
        """
        pass

    def get_initial_preference() -> Preference:
        """This method returns initial preference. the initial preference could be
        completed or uncompleted related to certainty or uncertainty respectively.
        """
        pass

    def get_offer_rank(offer : Offer) -> List:
        """This method returns a list of bids that exist special bid which has been sent
        to it.
        """
        pass

    def get_utility(offer : Offer) -> float:
        """This method returns exact utility of an offer
        """
        pass