#######################################################
# 
# UserModel.py
# Python implementation of the Interface UserModelInterface
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 01:26:23 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Preference import Preference

class UserModelInterface:
    def generate_initial_preference() -> Preference:
        pass