#######################################################
# 
# UserModel.py
# Python implementation of the Interface UserModel
# Generated by Enterprise Architect
# Created on:      26-ãÇÑÓ-2022 12:57:04 Ş.Ù
# Original author: DP
# 
#######################################################
from core.Preference import Preference

class UserModel:
    def generate_initial_preference() -> Preference:
        pass