#######################################################
#
# UtilitySpace.py
# Python implementation of the Class UtilitySpace
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Preference import Preference
from core.Bid import Bid
from core.Offer import Offer


class UtilitySpace:

    """
    In this class only linear utility function was developed.
    This class must be extended later
    """

    def __init__(self, preference):
        self.preference = preference

    def get_preference(self) -> Preference:
        return self.preference

    def get_utility(self, bid: Bid) -> float:
        weights = []
        scores = []
        total_score = 0
        for issue_value in bid.get_issues_items():
            weights.append(self.preference.get_issue_weight(issue_value[0]))
            score = self.preference.get_issue_item_value(issue_value[0], issue_value[1])
            total_score += score
            scores.append(score)

        utility = 0
        i = 0
        for weight in weights:
            utility += weight * (scores[i]/total_score)
            i += 1

        return utility

    def get_utility_distinct(self, offer: Offer) -> float:
        pass
