#######################################################
#
# UtiltiySpace.py
# Python implementation of the Class UtiltiySpace
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Preference import Preference
from core.Bid import Bid
from core.Offer import Offer


class UtiltiySpace:
    def get_preference(self) -> Preference:
        pass

    def get_utility(self, Bid: Bid) -> float:
        pass

    def get_utility_distict(self, offer: Offer) -> float:
        pass
