#######################################################
#
# UtiltiySpace.py
# Python implementation of the Class UtiltiySpace
# Generated by Enterprise Architect
# Created on:      26-����-2022 02:24:13 �.�
# Original author: DP
#
#######################################################
from core.Preference import Preference
from core.Bid import Bid
from core.Offer import Offer


class UtiltiySpace:
    def get_preference() -> Preference:
        pass

    def get_utility(Bid: Bid) -> double:
        pass

    def get_utility_distict(offer: Offer) -> double:
        pass
